---
- name: Deploy GPU Metrics Collector
  hosts: gpu_instances
  become: yes
  vars:
    collector_user: gpu-metrics
    collector_group: gpu-metrics
    collector_binary: gpu-metrics-collector
    config_dir: /etc/gpu-metrics
    working_dir: /var/lib/gpu-metrics
    log_dir: /var/log/gpu-metrics

  tasks:
    - name: Add startup SSH key to authorized_keys
      authorized_key:
        user: ubuntu
        key: "{{ startup_ssh_key }}"
        state: present
        comment: "vlgpus-startup-{{ instance_id }}"
      when: startup_ssh_key is defined and startup_ssh_key != ""

    - name: Create collector user and group
      group:
        name: "{{ collector_group }}"
        system: yes

    - name: Create collector user
      user:
        name: "{{ collector_user }}"
        group: "{{ collector_group }}"
        system: yes
        shell: /usr/sbin/nologin
        home: "{{ working_dir }}"
        create_home: no

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ collector_user }}"
        group: "{{ collector_group }}"
        mode: "0755"
      loop:
        - "{{ config_dir }}"
        - "{{ working_dir }}"
        - "{{ log_dir }}"

    - name: Copy collector binary
      copy:
        src: "{{ collector_binary }}"
        dest: "/usr/local/bin/{{ collector_binary }}"
        owner: root
        group: root
        mode: "0755"
      notify: restart gpu-metrics-collector

    - name: Generate collector configuration
      template:
        src: config.json.j2
        dest: "{{ config_dir }}/config.json"
        owner: "{{ collector_user }}"
        group: "{{ collector_group }}"
        mode: "0600"
      notify: restart gpu-metrics-collector

    - name: Install systemd service file
      copy:
        src: gpu-metrics-collector.service
        dest: /etc/systemd/system/gpu-metrics-collector.service
        owner: root
        group: root
        mode: "0644"
      notify:
        - reload systemd
        - restart gpu-metrics-collector

    - name: Enable and start gpu-metrics-collector service
      systemd:
        name: gpu-metrics-collector
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart gpu-metrics-collector
      systemd:
        name: gpu-metrics-collector
        state: restarted
